// This file is @generated by prost-build.
/// Message from the car (coordinates and speed)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VehiclePosition {
    #[prost(string, tag = "1")]
    pub vehicle_id: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub latitude: f64,
    #[prost(double, tag = "3")]
    pub longitude: f64,
    #[prost(double, tag = "4")]
    pub speed: f64,
    #[prost(int64, tag = "5")]
    pub timestamp: i64,
}
/// Traffic jam message (for analytics)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrafficJamAlert {
    #[prost(string, tag = "1")]
    pub road_id: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub avg_speed: f64,
    #[prost(int64, tag = "3")]
    pub timestamp: i64,
}
