// crates/common/src/lib.rs

// 1. Export the generated Protobuf code
pub mod proto {
    // Include the file generated by build.rs
    // It's located in the hidden target folder (OUT_DIR)
    // Note: We removed "/src/proto/" from the path because we simplified build.rs
    include!(concat!(env!("OUT_DIR"), "/traffic.rs"));
}

// 2. Make the structures accessible immediately from the library root
// Now you can write: use traffic_common::VehiclePosition;
pub use proto::*;


// Configuration settings
pub mod config;
pub use config::Config;

// Error handling
pub mod error;
pub use error::{Result, TrafficError};

// Logging and telemetry
pub mod telemetry;
pub use telemetry::init_tracing;